### PR TITLE
Added suffix 'Command' to all files under src/Command

### PR DESCRIPTION
**Pull request by CTZxVULKAN**
**All files** under `src/Command` have been provided with the suffix 'Command'.

### Demonstration

**Original filename**  -> **New filename**
* Ascii.php ->AsciiCommand.php

### CODE REVIEW

**Comment by programarivm** [comment]
@CTZxVULKAN the command names should be updated accordingly in the following files as well:

- `src/CommandContainer.php`
- `src/Socket.php`

Also, please note that I just updated the `src/Socket.php` file -- so my changes should be pulled into your branch as well.

Happy learning and coding! 

Thank you, and keep it up.

**Comment by CTZxVULKAN** [comment]
`src/CommandContainer.php` should be renamed to `src/CommandContainerCommand.php` right ?

**Comment by programarivm** [comment]
`src/CommandContainer.php` shouldn't be renamed, however the command names should be updated accordingly in these files:

- `src/CommandContainer.php`
- `src/Socket.php`

For example, the following needs an update as well in order for the app to run:

```
...
use ChessServer\Command\AcceptFriendRequest;
use ChessServer\Command\Ascii;
use ChessServer\Command\Castling;
use ChessServer\Command\Captures;
use ChessServer\Command\Fen;
use ChessServer\Command\HeuristicPicture;
use ChessServer\Command\History;
use ChessServer\Command\IsCheck;
use ChessServer\Command\IsMate;
use ChessServer\Command\Piece;
use ChessServer\Command\Pieces;
use ChessServer\Command\PlayFen;
use ChessServer\Command\Quit;
use ChessServer\Command\Start;
use ChessServer\Command\Status;
...
```

**Comment by CTZxVULKAN** [comment]
I see so the imports need to **fixed** in `src/CommandContainer` and `src/Socket.php` should be renamed right ?

**Comment by programarivm** [comment]
Exactly! Also the class names should be updated in all files that were renamed; for example; otherwise the app can't run because of multiple syntax errors being thrown:

`src/Command/AcceptFriendRequestCommand.php`:
```
<?php

namespace ChessServer\Command;

use Chess\PGN\Symbol;

class AcceptFriendRequestCommand extends AbstractCommand
{
    public function __construct()
    {
        $this->name = '/accept';
        $this->description = 'Accepts a friend request to play a game.';
        $this->params = [
            'id' => 'id',
        ];
        $this->dependsOn = [];
    }

    public function validate(array $argv)
    {
        return count($argv) - 1 === count($this->params);
    }
}
```

**Comment by CTZxVULKAN** [comment]
I see 
Will do soon :)

**Comment by CTZxVULKAN** [comment]
@programarivm  The following fixes were implemented corresponding to the [name changes](https://github.com/programarivm/chess-server/pull/30/commits/c9c07c9be11e752ac2c47688279f7271c4bc1d03).

Classnames in the following files have been modified : 

-    Command/AcceptFriendRequestCommand.php
-    Command/AsciiCommand.php
-    Command/CapturesCommand.php
-    Command/CastlingCommand.php
-    Command/FenCommand.php
-    Command/HeuristicPictureCommand.php
-    Command/HistoryCommand.php
-    Command/IsCheckCommand.php
-    Command/IsMateCommand.php
-    Command/PieceCommand.php
-    Command/PiecesCommand.php
-    Command/PlayFenCommand.php
-    Command/QuitCommand.php
-    Command/StartCommand.php
-    Command/StatusCommand.php

Imports have been fixed under `CommandContainer.php` & `Socket.php` has been moved to `SocketCommand.php`

**Comment by CTZxVULKAN** [comment]
Please feel free to merge as the code base was updated pertaining to the [sockets commit](https://github.com/programarivm/chess-server/commit/357af0778c9b01bdf69ce4866c8eab6d12289525) before making modifications.

**Comment by CTZxVULKAN** [comment]
Is this issue good enough to be closed now ?

**Pull request merged**
